# Site settings
title: 0 Byte
description: 0 Byte's Blog
url: 'http://www.infox.top/'
baseurl: /
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: '0 Byte'
  email: tzm192@foxmail.com
  twitter_username: tzm192
  facebook_username: infox.calm
#  github_username:  ****
#  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
#permalink: pretty
#permalink: /:year/:title/
permalink: /:title.html
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
